
version: "3"
services:
  web:
    build: .
    ports: ['8080:8080']
    volumes: ['.:/app']
    environment:
      - FLASK_DEBUG=1
      - ENV=DEV
      - OPENAI_API_KEY="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"
      # - CLIENT_SECRET=

#  redis:
#    image: redis