
version: "3"
services:
  web:
    build: .
    ports: ['8080:8080']
    volumes: ['.:/app']
    environment:
      - FLASK_DEBUG=1
      - ENV=DEV
      - OPENAI_API_KEY=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
      # - CLIENT_SECRET=

#  redis:
#    image: redis